### ISSUE TITLE
Submit Presentation Topics

### ISSUE THREAD

**Issue by ErSKS** [Khwopa/FOSP#11]
- Submit your presentation topics in the comment section below:
- Topics should be related to Free Software (FS), Open Software (OS), Open Source Software (OSS), Open Source Programming (OSP) or Free and Open Source Programming (FOSP).
- Deadline: 2 June 2019

**Comment by ayushbijukchhe** [comment]
Topic-Visual Studio Code

**Comment by izenish** [comment]
Topic: MySQL

**Comment by gauravchapagain** [comment]
Topic: GIMP (Image editor)

**Comment by KrishnadevAD** [comment]
Topic: LISP

**Comment by amanmool10** [comment]
Topic: WordPress

**Comment by Avishek-karki** [comment]
Topic: Android

**Comment by Sirish-Titaju** [comment]
Topic: FileZilla (FTP Software)

**Comment by SimantaKarki** [comment]
Topic: Eclipse

**Comment by Rawbeenprajapati** [comment]
VLC media player

**Comment by blank2019** [comment]
Audacity

**Comment by Sushant9818** [comment]
7zip

**Comment by omitbajracharya** [comment]
Topic:python

**Comment by reshadulal** [comment]
Topic: JavaScript

**Comment by kushalbadal** [comment]
Topic: PHP

**Comment by kkritii** [comment]
OpenShot (Video Editor)

**Comment by kkritii** [comment]
Topic : OpenShot (Video Editor)

**Comment by SababJuwal** [comment]
Topic: BitTorrent

**Comment by imrheaa** [comment]
Topic:java

**Comment by Nrshr** [comment]
Topic: Linux

**Comment by anilkarki979** [comment]
Topic : Moodle

**Comment by Rimpahang** [comment]
Topic : Blender

**Comment by chetana7** [comment]
Topic:HTML

**Comment by babin11** [comment]
Topic: Intenet Download Manager

**Comment by Aarju009** [comment]
Topic: Atom

**Comment by manis3** [comment]
TOPIC:Notepad

**Comment by susantyata** [comment]
Topic:Apache

**Comment by babin11** [comment]
Topic: Brave browser

**Comment by neetuphaiju** [comment]
R programming

**Comment by swostika2** [comment]
Topic: Ruby

**Comment by ShresthaKumarGaurav** [comment]
Topic: FreeDOS

**Comment by rodipduwal** [comment]
Zope

**Comment by KrishnadevAD** [comment]
Topic :CSS

**Comment by srijandangol** [comment]
Fedora

**Comment by Aakash-Chaudhary** [comment]
Topic: Samba

**Comment by bishalpau** [comment]
Topic:Perl

**Comment by Uramud** [comment]
Kai os

**Comment by BibekPradhan** [comment]
topic: Koha

**Comment by saugat447** [comment]
Topic:celestia

**Comment by manesha07** [comment]
Topic:Mozilla firefox

**Comment by Sas-KPra** [comment]
Rufus

**Comment by RabinPhaiju** [comment]
Topic: prolog

**Comment by PrathamDahal** [comment]
Topic: Mozilla Thunderbird

**Comment by bijay0** [comment]
topic: open solaris

**Comment by Dipen19shakya** [comment]
Topic:Netscape Navigator

**Comment by subekkaji07** [comment]
My topic-KRITA
